### ISSUE TITLE
Machine sequence matrix

### ISSUE THREAD

**Issue by alfasst** [earaujoassis/metaheuristics#7]
Since these are job shop scheduling problems, there should a machine sequence matrix.

**Comment by earaujoassis** [comment]
Hi, @alfasst. I'm not sure how you make your way into this project, but it is not intended to be used as open source library to solve Job shop scheduling problems. This project was created as a way to showcase the abilities of another project: [earaujoassis/evolve](https://github.com/earaujoassis/evolve). The Machine Sequence Matrix is a way to work with Job shop scheduling problems and create a schedule in metaheuristics as solutions, but I'm not using that representation in this project; instead, I'm using random keys: you could check http://pubsonline.informs.org/doi/abs/10.1287/ijoc.6.2.154 and https://link.springer.com/article/10.1007/s00170-009-2379-y for more information. Thank you.

**Comment by alfasst** [comment]
Okay. Got it. Thanks.
